#!/bin/sh

# bash-functions - miscellaneous bash functions for use in the Google Cloud platform

# Copyright (c) 2020 Jeffrey S. Levine
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# convert_zone_to_region PROG_NAME ZONE_VALUE EXIT_STATUS_IF_ERROR

convert_zone_to_region()
{
  PROG_NAME="$1"
  ZONE="$2"
  EXIT_STATUS="$3"

  REGION=`gcloud compute zones list --filter "name~^$ZONE$" --format="csv [no-heading] (region)"`
  if [ -z "$REGION" -a $EXIT_STATUS -ne 0 ]
  then
    echo $PROG_NAME: invalid zone
    exit $EXIT_STATUS
  fi

  echo $REGION
}

# convert_project_id_to_number PROG_NAME PROJECT_ID EXIT_STATUS_IF_ERROR

convert_project_id_to_number()
{
  PROG_NAME="$1"
  PROJECT_ID="$2"
  EXIT_STATUS="$3"

  PROJECT_NUMBER=`gcloud projects list --filter="PROJECT_ID~^$PROJECT_ID$" --format="csv [no-heading] (PROJECT_NUMBER)"`
  if [ -z "$PROJECT_NUMBER" -a $EXIT_STATUS -ne 0 ]
  then
    echo $PROG_NAME: invalid zone
    exit $EXIT_STATUS
  fi

  echo $PROJECT_NUMBER
}
